[general]
# The directory that will contain the generated nfts 
output_dir="output"

# Parameters specific to logging 
[general.logging]
# The name of the file that will contain the logs 
filename="generator.log" 

# The format of the messages 
format="%(name)s:%(levelname)s:%(message)s"